[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = [
  "pnpm --filter @emerald/shared build",
  "pnpm --filter @emerald/api run db:generate",
  "pnpm --filter @emerald/api run build"
]

[start]
cmd = "cd apps/api && pnpm run start"
